import './globals.css'
import localFont from "next/font/local";
import {Inter} from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider";
import Header from "@/components/header";
import {Toaster} from "@/components/ui/toaster"
import {Providers} from "@/components/provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
}
import type { Viewport } from 'next'

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    // Also supported by less commonly used
    // interactiveWidget: 'resizes-visual',
}

const departureMono = localFont({
    src: "./fonts/DepartureMono-Regular.woff",
    variable: "--font-departure-mono",
});

export default function DefaultLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`relative flex min-h-screen flex-col bg-grid-small-black/[0.2] font-[family-name:var(--font-departure-mono)] ${departureMono.variable} `}>
        <Providers>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                <Header/>
                    {children}
                <Toaster/>
            </ThemeProvider>
        </Providers>
        </body>
        </html>


    )

}
