import './globals.css'
import {Inter} from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider";
import Header from "@/components/header";
import {Toaster} from "@/components/ui/toaster"
import {Providers} from "@/components/provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DefaultLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={'relative flex min-h-screen flex-col'}>
        <Providers>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                <Header/>

                <section>
                    {children}
                </section>
                <Toaster/>
            </ThemeProvider>
        </Providers>
        </body>
        </html>


    )

}
